### PR TITLE
token introspect remove client id constraint

### LINKED ISSUE #364: Token introspection, it seems to work incorrectly
### Discussed in https://github.com/erlef/oidcc/discussions/362

<div type='discussions-op-text'>

<sup>Originally posted by **danj3** July 30, 2024</sup>
There's a line in oidcc_token_introspection.erl:extract_response:

```
            IntrospectionClientId == ClientId; IntrospectionClientId == undefined
```

Which seems to mean that the function will only introspect a token that was issued by the client of the caller (i.e. one's own token) or a token issued elsewhere but only to a client_id of the same name.
Somehow this seems incorrect and not very useful, but maybe I misunderstand the intent of these words (from https://datatracker.ietf.org/doc/html/rfc7662):

```
   This specification defines a protocol that allows authorized
   protected resources to query the authorization server to determine
   the set of metadata for a given token that was presented to them by
   an OAuth 2.0 client.  This metadata includes whether or not the token
   is currently active (or if it has expired or otherwise been revoked),
   what rights of access the token carries (usually conveyed through
   OAuth 2.0 scopes), and the authorization context in which the token
   was granted (including who authorized the token and which client it
  was issued to).  Token introspection allows a protected resource to
   query this information regardless of whether or not it is carried in
   the token itself, allowing this method to be used along with or
   independently of structured token values.  Additionally, a protected
   resource can use the mechanism described in this specification to
   introspect the token in a particular authorization decision context
   and ascertain the relevant metadata about the token to make this
   authorization decision appropriately.
```

It would seem that this constraint would just need to be removed to fix the problem. Unless there is another mechanism for validating a token through the AS?</div>

### PR DESCRIPTION
**Pull request by danj3**
resolves #364 

previously could only introspect a client_id's own token, introspect needs to be able to introspect any token for an issuer.

It is my understanding from https://datatracker.ietf.org/doc/html/rfc7662 that introspect endpoint is valid for use with any token from the issuer, however the code prior to this change would reject a token when the client_id in the token was not the same as the client_id of the caller to introspect.

### CODE REVIEW

**Comment by maennchen** [comment]
@danj3 Thanks for the PR.

I agree with your understanding of the RFC. A valid token issued to any client should return a successful response.

However, this function is used in many places as a validation for a specific client. We therefore can't change the behavior without making it a breaking change.

A major release would have to entail refreshing all certifications which is a considerable amount of work. For this change only, I don't think it is benefit enough.

I therefore propose the following:

* We introduce a new option `check_issued_client` (default: `false`)
* We add a [warning  admonition block](https://github.com/elixir-lang/ex_doc?tab=readme-ov-file#admonition-blocks) to the docs
* We'll keep the issue open until release 4.0 is happening.

File: src/oidcc_token_introspection.erl [hunk 1]
```diff
@@ -198,14 +218,11 @@ extract_response(TokenMap, #oidcc_client_context{client_id = ClientId}) ->
     Aud = maps:get(<<"aud">>, TokenMap, undefined),
     Iss = maps:get(<<"iss">>, TokenMap, undefined),
     Jti = maps:get(<<"jti">>, TokenMap, undefined),
-    case maps:get(<<"client_id">>, TokenMap, undefined) of
-        IntrospectionClientId when
-            IntrospectionClientId == ClientId; IntrospectionClientId == undefined
-        ->
-            {ok, #oidcc_token_introspection{
+    Cid = maps:get(<<"client_id">>, TokenMap, undefined),
```
Comment (maennchen) [inline src/oidcc_token_introspection.erl:221]:
```suggestion
    ClientId = maps:get(<<"client_id">>, TokenMap, undefined),
```

**Review by maennchen — DISMISSED** [review]
